name: "AKS Microservices Workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-init-plan:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
       
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: e0a7672f-5903-4d93-9d70-5dadafa94bc6
          tenant-id: 963eb818-eef0-442e-a584-03a5e8fbb97f
          subscription-id: dc1b0d18-b7a7-4981-90c1-5f01ea6fc258

      - name: Terraform FMT
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: Environment/dev

      - name: Terraform INIT
        id: init
        run: terraform init -input=false
        working-directory: Environment/dev

      - name: Terraform VALIDATE
        id: validate
        run: terraform validate -no-color
        working-directory: Environment/dev

      - name: Terraform PLAN
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: Environment/dev

  terraform-apply:    
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    needs: terraform-init-plan
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # ya tu apna custom action use kar sakta hai:
        # uses: ranjeet-112/my-action@v1

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: e0a7672f-5903-4d93-9d70-5dadafa94bc6
          tenant-id: 963eb818-eef0-442e-a584-03a5e8fbb97f
          subscription-id: dc1b0d18-b7a7-4981-90c1-5f01ea6fc258

      - name: Terraform INIT
        id: init
        run: terraform init -input=false
        working-directory: Environment/dev

      - name: Terraform APPLY
        id: apply
        run: terraform apply -auto-approve
        continue-on-error: true
        working-directory: Environment/dev
